// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhWlGfXE-pQfMf-g4tmIVYKYs8kM76S-w',
    appId: '1:111136972005:web:95a79d79328ee5c7d6480c',
    messagingSenderId: '111136972005',
    projectId: 'thermalguesser',
    authDomain: 'thermalguesser.firebaseapp.com',
    storageBucket: 'thermalguesser.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhmhl_urgvMuKdFzt63kS_F5z2GVzedD4',
    appId: '1:111136972005:android:b6d89fc45de8e4edd6480c',
    messagingSenderId: '111136972005',
    projectId: 'thermalguesser',
    storageBucket: 'thermalguesser.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk45eaI1lSycKrY_SPFTOT2cR6VHiupB4',
    appId: '1:111136972005:ios:c7137215659b5fa2d6480c',
    messagingSenderId: '111136972005',
    projectId: 'thermalguesser',
    storageBucket: 'thermalguesser.firebasestorage.app',
    iosBundleId: 'com.thermalguesser.appThermalGuesser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk45eaI1lSycKrY_SPFTOT2cR6VHiupB4',
    appId: '1:111136972005:ios:c7137215659b5fa2d6480c',
    messagingSenderId: '111136972005',
    projectId: 'thermalguesser',
    storageBucket: 'thermalguesser.firebasestorage.app',
    iosBundleId: 'com.thermalguesser.appThermalGuesser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhWlGfXE-pQfMf-g4tmIVYKYs8kM76S-w',
    appId: '1:111136972005:web:53cda4bd5c204e09d6480c',
    messagingSenderId: '111136972005',
    projectId: 'thermalguesser',
    authDomain: 'thermalguesser.firebaseapp.com',
    storageBucket: 'thermalguesser.firebasestorage.app',
  );
}